version: "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: celestia-bridge-health-checker-backend
    ports:
      - "3001:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: celestia-bridge-health-checker
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000
